<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SRIKJ-M-M38C" name="AppTest" tests="6" failures="3" timestamp="28 Apr 2017 09:42:13 GMT" time="0.032" errors="0">
  <testcase name="failingTest" time="0.009" classname="com.cisco.test.jenkinsTest.SampleTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.cisco.test.jenkinsTest.SampleTest.failingTest(SampleTest.java:35)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- failingTest -->
  <testcase name="failingTest1" time="0.0" classname="com.cisco.test.jenkinsTest.SampleTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.cisco.test.jenkinsTest.SampleTest.failingTest1(SampleTest.java:40)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- failingTest1 -->
  <testcase name="failingTest2" time="0.0" classname="com.cisco.test.jenkinsTest.SampleTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.cisco.test.jenkinsTest.SampleTest.failingTest2(SampleTest.java:45)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- failingTest2 -->
  <testcase name="passingTest" time="0.001" classname="com.cisco.test.jenkinsTest.SampleTest"/>
  <testcase name="passingTest1" time="0.0" classname="com.cisco.test.jenkinsTest.SampleTest"/>
  <testcase name="passingTest2" time="0.001" classname="com.cisco.test.jenkinsTest.SampleTest"/>
</testsuite> <!-- AppTest -->
